--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	E:/work_icda/yuanxingji/4/camera_mipi_ddr_hdmi/td_project/al_ip/blk_mem_gen_0.vhd
 -- Date	:	2024 11 06
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY blk_mem_gen_0 IS
PORT (
	dob	: OUT STD_LOGIC_VECTOR(7 DOWNTO 0);

	dia	: IN STD_LOGIC_VECTOR(7 DOWNTO 0);
	addra	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	cea	: IN STD_LOGIC;
	clka	: IN STD_LOGIC;
	addrb	: IN STD_LOGIC_VECTOR(9 DOWNTO 0);
	clkb	: IN STD_LOGIC;
	rstb	: IN STD_LOGIC
	);
END blk_mem_gen_0;

ARCHITECTURE struct OF blk_mem_gen_0 IS

	BEGIN
	inst : PH1_LOGIC_ERAM
		GENERIC MAP (
			DATA_WIDTH_A	=> 8,
			DATA_WIDTH_B	=> 8,
			ADDR_WIDTH_A	=> 10,
			ADDR_WIDTH_B	=> 10,
			DATA_DEPTH_A	=> 960,
			DATA_DEPTH_B	=> 960,
			MODE		=> "PDPW",
			REGMODE_A	=> "NOREG",
			REGMODE_B	=> "OUTREG",
			WRITEMODE_A	=> "NORMAL",
			WRITEMODE_B	=> "NORMAL",
			IMPLEMENT	=> "20K",
			CLKMODE		=> "ASYNC",
			ECC_ENCODE		=> "DISABLE",
			ECC_DECODE		=> "DISABLE",
			SSROVERCE		=> "DISABLE",
			OREGSET_A		=> "SET",
			OREGSET_B		=> "SET",
			RESETMODE_A		=> "ASYNC",
			RESETMODE_B		=> "ASYNC",
			ASYNC_RESET_RELEASE_A		=> "SYNC",
			ASYNC_RESET_RELEASE_B		=> "SYNC",
			INIT_FILE		=> "NONE",
			FILL_ALL		=> "NONE"
		)
		PORT MAP (
			dia	=> dia,
			dib	=> (others=>'0'),
			addra	=> addra,
			addrb	=> addrb,
			cea	=> cea,
			ceb	=> '1',
			clka	=> clka,
			clkb	=> clkb,
			wea	=> '1',
			web	=> '0',
			bea	=> (others=>'0'),
			beb	=> (others=>'0'),
			ocea	=> '0',
			oceb	=> '1',
			rsta	=> '0',
			rstb	=> rstb,
			ecc_sbiterr	=> OPEN,
			ecc_dbiterr	=> OPEN,
			ecc_sbiterrinj	=> OPEN,
			ecc_dbiterrinj	=> OPEN,
			doa	=> OPEN,
			dob	=> dob
		);

END struct;
