/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/zhang/Desktop/work/FPGA/PH1/Verimake_camera_mipi_ddr_hdmi/user_source/ip_source/w32_d480_shifter.v
 ** Date	:	2023 09 05
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module w32_d480_shifter(dataout,
	clk, en, datain);

    input                     clk;
    input                     en;
    input       [31:0]      datain;
    output      [31:0]      dataout;
    PH1_LOGIC_SHIFTER#(
        .DATA_WIDTH(32),
        .DATA_DEPTH(480),
        .INIT_FILE("NONE"),
        .SHIFT_TYPE("FIXED"))
        inst(
         .depth({1{1'b0}}),
         .dataout(dataout),
         .clk(clk),
         .en(en),
         .datain(datain));

endmodule
