--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/zhang/Desktop/work/FPGA/PH1/Verimake_camera_mipi_ddr_hdmi/user_source/ip_source/w32_d962_shifter.vhd
 -- Date	:	2023 09 05
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY w32_d962_shifter IS
PORT (
    clk	: IN STD_LOGIC;
    en	: IN STD_LOGIC;
    datain	: IN STD_LOGIC_VECTOR(31 DOWNTO 0);

    dataout	: OUT STD_LOGIC_VECTOR(31 DOWNTO 0)

);
END w32_d962_shifter;

ARCHITECTURE struct OF w32_d962_shifter IS

    BEGIN
        inst : PH1_LOGIC_SHIFTER
            GENERIC MAP (
                DATA_WIDTH => 32,
                DATA_DEPTH => 962,
                INIT_FILE	=> "NONE",
                SHIFT_TYPE => "FIXED"
            )
            PORT MAP (
                depth => (others=>'0'),
                clk	=> clk,
                en	=> en,
                datain	=> datain,
                dataout	=> dataout
            );

END struct;
