--------------------------------------------------------------
 --     Copyright (c) 2012-2023 Anlogic Inc.
 --  All Right Reserved.
--------------------------------------------------------------
 -- Log	:	This file is generated by Anlogic IP Generator.
 -- File	:	C:/Users/zhang/Desktop/FPGA/ph1/Verimake_camera_mipi_ddr_hdmi_3/user_source/ip_source/w40_d512_fifo.vhd
 -- Date	:	2023 09 22
 -- TD version	:	5.6.71036
--------------------------------------------------------------

LIBRARY ieee;
USE work.ALL;
	USE ieee.std_logic_1164.all;
LIBRARY ph1_macro;
	USE ph1_macro.PH1_COMPONENTS.all;

ENTITY w40_d512_fifo IS
PORT (
	di	: IN STD_LOGIC_VECTOR(39 DOWNTO 0);

	rst	: IN STD_LOGIC;
	clk	: IN STD_LOGIC;
	we	: IN STD_LOGIC;
	re	: IN STD_LOGIC;
	dout	: OUT STD_LOGIC_VECTOR(39 DOWNTO 0);
	empty_flag		: OUT STD_LOGIC;
	full_flag		: OUT STD_LOGIC;
	rdusedw			: OUT STD_LOGIC_VECTOR(8 DOWNTO 0);
	wrusedw			: OUT STD_LOGIC_VECTOR(8 DOWNTO 0)
	);
END w40_d512_fifo;

ARCHITECTURE struct OF w40_d512_fifo IS

	BEGIN
	inst : PH1_LOGIC_RAMFIFO
		GENERIC MAP (
			DATA_WIDTH			=> 40,
			ADDR_WIDTH			=> 8,
			SHOWAHEAD			=> 0,
			IMPLEMENT			=>"20K(FAST)"
		)
		PORT MAP (
			rst	=> rst,
			di	=> di,
			clk	=> clk,
			we	=> we,
			re	=> re,
			dout	=> dout,
			empty_flag	=> empty_flag,
			full_flag	=> full_flag,
			rdusedw		=> rdusedw,
			wrusedw		=> wrusedw
		);

END struct;
