/************************************************************\
 **     Copyright (c) 2012-2023 Anlogic Inc.
 **  All Right Reserved.\
\************************************************************/
/************************************************************\
 ** Log	:	This file is generated by Anlogic IP Generator.
 ** File	:	C:/Users/zhang/Desktop/FPGA/ph1/Verimake_camera_mipi_ddr_hdmi_3/user_source/ip_source/w40_d512_fifo.v
 ** Date	:	2023 09 22
 ** TD version	:	5.6.71036
\************************************************************/

`timescale 1ns / 1ps

module w40_d512_fifo (
	rst,
	di, re, clk, we,
	dout,
	empty_flag,full_flag,rdusedw,wrusedw
 
);

	input rst;
	input [39:0] di;
	input clk, we;
	input re;

	output [39:0] dout;
	output empty_flag;
	output full_flag;
	output [8:0] rdusedw;
	output [8:0] wrusedw;

PH1_LOGIC_RAMFIFO #(
 	.DATA_WIDTH(40),
	.ADDR_WIDTH(8),
	.SHOWAHEAD(0),
	.IMPLEMENT("20K(FAST)")
)
logic_ramfifo(
	.rst(rst),
	.di(di),
	.clk(clk),
	.we(we),
	.dout(dout),
	.re(re),
	.empty_flag(empty_flag),
	.full_flag(full_flag),
	.rdusedw(rdusedw),
	.wrusedw(wrusedw)
);

endmodule